import type { CustomTool, RFEdge, RFNode } from "../types/agent-builder";

type GeneratorSettings = {
  instructions?: string;
  includeChatHistory?: boolean;
  model?: string;
  outputFormat?: "text" | "json";
  codeLanguage?: "javascript" | "typescript";
};

type GeneratorOptions = {
  agentId?: string;
  agentName?: string;
  customTools?: CustomTool[];
  settings?: GeneratorSettings;
};

function escapeTemplate(value: string) {
  return value.replace(/`/g, "\\`");
}

function normalizeNode(node: RFNode) {
  return {
    id: node.id,
    label: String(node.data?.label || node.id),
    type: String(node.data?.type || node.type || "default"),
    config: node.data?.config || {},
    position: node.position,
  };
}

export function generateAgentCode(
  nodes: RFNode[],
  edges: RFEdge[],
  agentType = "custom",
  options: GeneratorOptions = {}
): string {
  const agentName = options.agentName || "NOVA Agent";
  const customTools = options.customTools || [];
  const settings = options.settings || {};
  const language = settings.codeLanguage || "javascript";
  const isTs = language === "typescript";
  const serializedNodes = nodes.map(normalizeNode);

  return `${isTs ? "/* eslint-disable no-console */" : "#!/usr/bin/env node"}
/**
 * Auto-generated by NOVA Agent Builder
 * Agent Name: ${escapeTemplate(agentName)}
 * Agent ID: ${escapeTemplate(options.agentId || "unknown")}
 * Agent Type: ${escapeTemplate(agentType)}
 *
 * Usage:
 * 1. Set OPENAI_API_KEY in your environment.
 * 2. Run: node ${isTs ? "generated-agent.ts" : "generated-agent.js"} "your prompt"
 */

const AGENT = ${JSON.stringify(
    {
      id: options.agentId || "",
      name: agentName,
      type: agentType,
      settings: {
        instructions: settings.instructions || "",
        includeChatHistory: settings.includeChatHistory ?? true,
        model: settings.model || "gpt-5",
        outputFormat: settings.outputFormat || "text",
      },
      nodes: serializedNodes,
      edges,
      customTools,
    },
    null,
    2
  )};

${isTs ? "type WorkflowState = Record<string, unknown>;" : ""}

function slugify(value${isTs ? ": string" : ""}) {
  return String(value || "step")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

async function callOpenAI(prompt${isTs ? ": string" : ""}, workflowState${isTs ? ": Record<string, unknown>" : ""}) {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    return {
      mode: "offline",
      content:
        "OPENAI_API_KEY is not set. The workflow still ran, but the model response is in offline mode.",
    };
  }

  const systemPrompt = [
    \`You are \${AGENT.name}.\`,
    AGENT.settings.instructions || "Follow the configured workflow and tools exactly.",
    "Workflow nodes:",
    JSON.stringify(AGENT.nodes, null, 2),
    "Workflow edges:",
    JSON.stringify(AGENT.edges, null, 2),
    "Custom tools:",
    JSON.stringify(AGENT.customTools, null, 2),
    "Current workflow state:",
    JSON.stringify(workflowState, null, 2),
  ].join("\\n\\n");

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: \`Bearer \${apiKey}\`,
    },
    body: JSON.stringify({
      model: AGENT.settings.model || "gpt-5",
      input: [
        {
          role: "system",
          content: [{ type: "input_text", text: systemPrompt }],
        },
        {
          role: "user",
          content: [{ type: "input_text", text: prompt }],
        },
      ],
      text: {
        format:
          AGENT.settings.outputFormat === "json"
            ? { type: "json_object" }
            : { type: "text" },
      },
    }),
  });

  const payload = await response.json();
  if (!response.ok) {
    throw new Error(payload?.error?.message || "OpenAI request failed");
  }

  const fallback =
    payload?.output_text ||
    payload?.output?.map?.((item${isTs ? ": any" : ""}) => item?.content?.map?.((part${isTs ? ": any" : ""}) => part?.text).join("")).join("\\n") ||
    "";

  return {
    mode: "openai",
    content: fallback,
    raw: payload,
  };
}

async function executeHttpTool(tool${isTs ? ": any" : ""}, prompt${isTs ? ": string" : ""}, state${isTs ? ": Record<string, unknown>" : ""}) {
  if (!tool.apiUrl) {
    return {
      ok: false,
      skipped: true,
      reason: "Missing apiUrl",
    };
  }

  const method = (tool.method || "GET").toUpperCase();
  const shouldSendBody = ["POST", "PUT", "PATCH", "DELETE"].includes(method);
  const response = await fetch(tool.apiUrl, {
    method,
    headers: {
      "Content-Type": "application/json",
    },
    body: shouldSendBody
      ? JSON.stringify({
          prompt,
          state,
          params: tool.paramsSchema || {},
        })
      : undefined,
  });

  const contentType = response.headers.get("content-type") || "";
  const data = contentType.includes("application/json")
    ? await response.json()
    : await response.text();

  return {
    ok: response.ok,
    status: response.status,
    data,
  };
}

async function runWorkflow(prompt${isTs ? ": string" : ""})${isTs ? ": Promise<WorkflowState>" : ""} {
  const state${isTs ? ": WorkflowState" : ""} = {
    prompt,
    visitedNodes: [],
  };

  for (const node of AGENT.nodes) {
    const key = slugify(node.label || node.id);
    const type = node.type;
    const config = node.config || {};
    state.visitedNodes.push(node.id);

    if (type === "api") {
      state[key] = await executeHttpTool(
        {
          apiUrl: config.apiUrl,
          method: config.method || "GET",
          paramsSchema: config.paramsSchema || {},
        },
        prompt,
        state
      );
      continue;
    }

    if (type === "custom") {
      const tool = AGENT.customTools.find((item${isTs ? ": any" : ""}) => item.id === config.toolId);
      state[key] = tool
        ? await executeHttpTool(tool, prompt, state)
        : { ok: false, skipped: true, reason: "Custom tool not found" };
      continue;
    }

    if (type === "if") {
      state[key] = {
        branch: config.condition || "manual-condition",
        evaluated: true,
      };
      continue;
    }

    if (type === "while") {
      state[key] = {
        loop: config.condition || "manual-loop",
        maxIterations: config.maxIterations || 3,
      };
      continue;
    }

    state[key] = {
      type,
      label: node.label,
      config,
    };
  }

  return state;
}

async function runAgent(prompt${isTs ? ": string" : ""}, chatHistory${isTs ? ": Array<{ role: string; content: string }> = []" : " = []"}) {
  const workflow = await runWorkflow(prompt);
  if (AGENT.settings.includeChatHistory) {
    workflow.chatHistory = chatHistory;
  }

  const completion = await callOpenAI(prompt, workflow);
  return {
    agent: AGENT.name,
    mode: completion.mode,
    workflow,
    reply:
      AGENT.settings.outputFormat === "json" && typeof completion.content === "string"
        ? JSON.parse(completion.content)
        : completion.content,
  };
}

async function main() {
  const prompt = process.argv.slice(2).join(" ").trim();

  if (!prompt) {
    console.error('Usage: node generated-agent.${isTs ? "ts" : "js"} "your prompt"');
    process.exit(1);
  }

  const result = await runAgent(prompt);
  console.log(
    typeof result.reply === "string"
      ? result.reply
      : JSON.stringify(result.reply, null, 2)
  );
}

if (typeof require !== "undefined" && require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

${isTs ? "export { AGENT, runAgent, runWorkflow };" : "module.exports = { AGENT, runAgent, runWorkflow };"}
`;
}
